<a href="https://colab.research.google.com/github/a-forty-two/diamler_17_jan/blob/main/01_Normalization_and_Outliers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Age, Money(lakhs), Happiness
# 10 , 0 ,   1
# 50 , 1000, 0
# 25 , 500, 0
# 35 , 650, 1
# order of Age-> 1,5,2.5,3.5 X 10^1-> Order 1
# order of Money-> 0, 1, 0.5, 0.65 X 10^8-> order 8
# order of Happiness-> 0,1 X 10^0-> Order 0
# The order is NOT same!
# Some columns hold values that are MUCH larger or smaller than 
# other columns!

In [2]:
# ML is y = mx + c
# m is weights, c is bias
# y = happiness = f(x1,x2) = weights * (Age,Money) + bias
# Happiness = w1*Age + w2*Money +bias 
# doesn't matter what Age's value is, Money is a large number
# and will always dominate the equation!

In [ ]:
# Central Limit Theorem 
# mean (centre of the circle), standard_deviation (radius of the circle)
# most points -> lesser length than standard deviation (inside the circle)
# some points-> can be > len(std), (on the circumference or just outside up to 2x STD)
# outliers-> distance from mean > 3 times the standard deviation!!!

In [3]:
import pandas as pd
data = pd.read_csv('https://raw.githubusercontent.com/a-forty-two/cylons/master/data.csv')

In [20]:
data.head()
data = data.iloc[:, :-1] # letting go for Unnamed: 32 columns
data.head()

         id diagnosis  ...  symmetry_worst  fractal_dimension_worst
0    842302         M  ...          0.4601                  0.11890
1    842517         M  ...          0.2750                  0.08902
2  84300903         M  ...          0.3613                  0.08758
3  84348301         M  ...          0.6638                  0.17300
4  84358402         M  ...          0.2364                  0.07678

[5 rows x 32 columns]

In [8]:
# ALL the data in the SAME SCALE- RATIO should be PRESERVED!

In [ ]:
# MinMax-> Make min number as 0, max number as 1, and scale
# everything in between 0 to 1

# Z-Score-> Make the mean as 0, standard deviation as our tolerance
# distance of any point(x) to mean-> x-mean
# if i were to divide this distance by std:
# for normal points => -1 < (x-mean)/std < 1
# for normal points up to outlier=> -3< (x-Mean)/std < 3
# for outliers=> -3> (x-mean)/std > 3

In [9]:
#MinMax -> Scale -> [0,1]
# formulae: for any dataset x, minmax = (x-min)/(max-min)
# for example, take pixels-> R,G,B
# (200,100,50) -> assume min (0,5,5) and max (200,200,200) from dataset
# (200-0, 100-5, 50-5) / (200-0, 200-5, 200-5)
# (200,95,45)/ (200, 195, 195)
# (1, 0.487, 0.231 )
# pictures, colors-> use MinMax

In [ ]:
# y = w1*r + w2*b + w3*g + bias
# r,g,b -> diff scales-> g (0,10) r(0,200) b (50,150)

In [21]:
stats = data.describe().T
minmax_min = stats['min']
minmax_max = stats['max']

In [22]:
scaled_minmax_dataset = (data-minmax_min)/(minmax_max - minmax_min)
scaled_minmax_dataset.head()

   area_mean   area_se  area_worst  ...  texture_mean  texture_se  texture_worst
0   0.363733  0.273811    0.450698  ...      0.022658    0.120469       0.141525
1   0.501591  0.125660    0.435214  ...      0.272574    0.082589       0.303571
2   0.449417  0.162922    0.374508  ...      0.390260    0.094303       0.360075
3   0.102906  0.038155    0.094008  ...      0.360839    0.175875       0.385928
4   0.489290  0.163688    0.341575  ...      0.156578    0.093065       0.123934

[5 rows x 32 columns]

In [18]:
minmax_max, minmax_min

(id                         9.113205e+08
 radius_mean                2.811000e+01
 texture_mean               3.928000e+01
 perimeter_mean             1.885000e+02
 area_mean                  2.501000e+03
 smoothness_mean            1.634000e-01
 compactness_mean           3.454000e-01
 concavity_mean             4.268000e-01
 concave points_mean        2.012000e-01
 symmetry_mean              3.040000e-01
 fractal_dimension_mean     9.744000e-02
 radius_se                  2.873000e+00
 texture_se                 4.885000e+00
 perimeter_se               2.198000e+01
 area_se                    5.422000e+02
 smoothness_se              3.113000e-02
 compactness_se             1.354000e-01
 concavity_se               3.960000e-01
 concave points_se          5.279000e-02
 symmetry_se                7.895000e-02
 fractal_dimension_se       2.984000e-02
 radius_worst               3.604000e+01
 texture_worst              4.954000e+01
 perimeter_worst            2.512000e+02
 area_worst                 4.254000e+03
 smoothness_worst           2.226000e-01
 compactness_worst          1.058000e+00
 concavity_worst            1.252000e+00
 concave points_worst       2.910000e-01
 symmetry_worst             6.638000e-01
 fractal_dimension_worst    2.075000e-01
 Unnamed: 32                         NaN
 Name: max, dtype: float64, id                         8670.000000
 radius_mean                   6.981000
 texture_mean                  9.710000
 perimeter_mean               43.790000
 area_mean                   143.500000
 smoothness_mean               0.052630
 compactness_mean              0.019380
 concavity_mean                0.000000
 concave points_mean           0.000000
 symmetry_mean                 0.106000
 fractal_dimension_mean        0.049960
 radius_se                     0.111500
 texture_se                    0.360200
 perimeter_se                  0.757000
 area_se                       6.802000
 smoothness_se                 0.001713
 compactness_se                0.002252
 concavity_se                  0.000000
 concave points_se             0.000000
 symmetry_se                   0.007882
 fractal_dimension_se          0.000895
 radius_worst                  7.930000
 texture_worst                12.020000
 perimeter_worst              50.410000
 area_worst                  185.200000
 smoothness_worst              0.071170
 compactness_worst             0.027290
 concavity_worst               0.000000
 concave points_worst          0.000000
 symmetry_worst                0.156500
 fractal_dimension_worst       0.055040
 Unnamed: 32                        NaN
 Name: min, dtype: float64)

In [23]:
# Z-scoring-> scales data, additionally help detect outliers

In [24]:
# formulae-> distance from mean/std
# -> (x-mean)/std
# scale-> -inf to + inf with mean set to 0!
# all values below -3 and above 3 are outliers
# after removing outliers, the scale-> (-3,3)

In [ ]:
# methodology:
# take assumptions from training dataset, apply those assumptions to the testing
# dataset
# assumptions-> mean, std, min, max

In [27]:
y = data.loc[:, 'diagnosis'] # loc-> location name
x = data.iloc[:, 2:12] # iloc-> index of location

In [28]:
x.head()

   radius_mean  texture_mean  ...  symmetry_mean  fractal_dimension_mean
0        17.99         10.38  ...         0.2419                 0.07871
1        20.57         17.77  ...         0.1812                 0.05667
2        19.69         21.25  ...         0.2069                 0.05999
3        11.42         20.38  ...         0.2597                 0.09744
4        20.29         14.34  ...         0.1809                 0.05883

[5 rows x 10 columns]

In [29]:
# divide the data between 2 datasets
# first dataset (training) > second dataset (Scoring or testing)
# testing dataset should not contain any new use cases!

In [30]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(x, y, test_size=0.2, random_state=42)

In [31]:
#get the assumptions from training data (xtrain)
# assumptions-> mean,std
stats = xtrain.describe().T
zmean = stats['mean']
zstd = stats['std']

In [32]:
# Apply the assumptions to both TRAINING and TESTING data
# z-score -> (data-mean)/std
xtrain_norm = (xtrain - zmean)/zstd
xtest_norm = (xtest - zmean)/zstd

# if the group says their fav color is blue
# and if i were to divide that group into 2
# those subgroups should also tell their fav color is blue!

In [34]:
# zscore-> mean is assumed 0, and all other values are scaled with respect to 
# mean and std
xtrain_norm.head()

     radius_mean  texture_mean  ...  symmetry_mean  fractal_dimension_mean
68     -1.439169     -0.434841  ...       1.091461                2.455470
181     1.971926      1.731120  ...       2.124665                1.556682
63     -1.398443     -1.248248  ...       1.928211                0.953329
248    -0.980717      1.414665  ...       0.312920                0.073960
60     -1.116471     -1.009149  ...       3.390704                0.949168

[5 rows x 10 columns]

In [42]:
# total outliers per column!
xtrain_norm[xtrain_norm > 3].count() + xtrain_norm[xtrain_norm < -3].count()

radius_mean               4
texture_mean              4
perimeter_mean            6
area_mean                 7
smoothness_mean           5
compactness_mean          6
concavity_mean            6
concave points_mean       5
symmetry_mean             4
fractal_dimension_mean    7
dtype: int64

radius_mean               0
texture_mean              0
perimeter_mean            0
area_mean                 0
smoothness_mean           1
compactness_mean          0
concavity_mean            0
concave points_mean       0
symmetry_mean             0
fractal_dimension_mean    0
dtype: int64